# **Terra Telefonica**

## Importações

In [2]:
# instalação de pacotes (se necessários)
#%pip install pandas numpy matplotlib plotly seaborn scikit-learn
#%pip install "nbformat>=4.2.0"

In [3]:
# Importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

## Camada Bronze

In [4]:
# Leitura do arquivo CSV
df = pd.read_csv('history.csv', encoding="utf-8", sep=",")

In [5]:
df.shape

(5634, 23)

In [6]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

## Camada Silver

### Tradução e categorização das colunas

In [7]:
#Tradução dos nomes das colunas
df.rename(columns={
    "customerID": "id_cliente",
    "gender": "Genero",
    "SeniorCitizen": "Senioridade",
    "Partner": "Parceiro",
    "Dependents": "Dependentes",
    "tenure": "DuracaoContrato",
    "PhoneService": "ServicoTelefonico",
    "MultipleLines": "MultiplasLinhas",
    "InternetService": "ServicoInternet",
    "OnlineSecurity": "SegurancaOnline",
    "OnlineBackup": "BackupOnline",
    "DeviceProtection": "ProtecaoDispositivo",
    "TechSupport": "SuporteTecnico",
    "StreamingTV": "StreamingTV",
    "StreamingMovies": "StreamingFilmes",
    "Contract": "Contrato",
    "PaperlessBilling": "FaturaEletronica",
    "PaymentMethod": "MetodoPagamento",
    "MonthlyCharges": "CobrancaMensal",
    "TotalCharges": "CobrancaTotal",
    "Churn": "Cancelamento",
    "CustomerFeedback": "FeedbackCliente",
    "MonthlyIncome": "RendaMensal",
}, inplace=True)

C:\Users\47729169894\AppData\Local\Temp\ipykernel_22356\1403478023.py:2: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.rename(columns={

In [8]:
df.head()

,id_cliente,Genero,Senioridade,Parceiro,Dependentes,DuracaoContrato,ServicoTelefonico,MultiplasLinhas,ServicoInternet,SegurancaOnline,...,StreamingTV,StreamingFilmes,Contrato,FaturaEletronica,MetodoPagamento,CobrancaMensal,CobrancaTotal,Cancelamento,FeedbackCliente,RendaMensal
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

In [9]:
# Verificando os tipos de dados das colunas
df.dtypes

id_cliente                 str
Genero                     str
Senioridade              int64
Parceiro                   str
Dependentes                str
DuracaoContrato            str
ServicoTelefonico          str
MultiplasLinhas            str
ServicoInternet            str
SegurancaOnline            str
BackupOnline               str
ProtecaoDispositivo        str
SuporteTecnico             str
StreamingTV                str
StreamingFilmes            str
Contrato                   str
FaturaEletronica           str
MetodoPagamento            str
CobrancaMensal         float64
CobrancaTotal          float64
Cancelamento               str
FeedbackCliente            str
RendaMensal              int64
dtype: object

In [10]:
# Categorização correta das colunas
df = df.astype({
    "Genero": "category",
    "Senioridade": "category",
    "Parceiro": "category",
    "Dependentes": "category",
    "ServicoTelefonico": "category",
    "MultiplasLinhas": "category",
    "ServicoInternet": "category",
    "SegurancaOnline": "category",
    "BackupOnline": "category",
    "ProtecaoDispositivo": "category",
    "SuporteTecnico": "category",
    "StreamingTV": "category",
    "StreamingFilmes": "category",
    "Contrato": "category",
    "FaturaEletronica": "category",
    "MetodoPagamento": "category",
    "Cancelamento": "category",
})

In [11]:
# Análise da coluna "DuracaoContrato"
df["DuracaoContrato"].value_counts(dropna=False)

DuracaoContrato
1          475
72         266
2          188
3          161
4          144
          ...
44          41
36          39
39          37
unknown     19
0           10
Name: count, Length: 74, dtype: int64

In [12]:
# Conversão da coluna "DuracaoContrato" para o tipo numérico, tratando valores não numéricos como NaN
df["DuracaoContrato"] = (
    pd.to_numeric(df["DuracaoContrato"], errors="coerce")
    .astype("Int64")
)

# Conversão das colunas restantes para os tipos de dados apropriados
df = df.astype({
    "id_cliente": "string",
    "CobrancaMensal": "float64",
    "CobrancaTotal": "float64",
    "FeedbackCliente": "string",
    "Senioridade": "Int64",
    "RendaMensal": "Int64",
    "DuracaoContrato": "Int64",
})

In [13]:
df.dtypes

id_cliente               string
Genero                 category
Senioridade               Int64
Parceiro               category
Dependentes            category
DuracaoContrato           Int64
ServicoTelefonico      category
MultiplasLinhas        category
ServicoInternet        category
SegurancaOnline        category
BackupOnline           category
ProtecaoDispositivo    category
SuporteTecnico         category
StreamingTV            category
StreamingFilmes        category
Contrato               category
FaturaEletronica       category
MetodoPagamento        category
CobrancaMensal          float64
CobrancaTotal           float64
Cancelamento           category
FeedbackCliente          string
RendaMensal               Int64
dtype: object

In [14]:
df.dtypes.map(lambda t: t.name).value_counts()

category    16
Int64        3
string       2
float64      2
Name: count, dtype: int64

### Camada Gold

In [15]:
df_gold = df.copy()

In [16]:
import plotly.express as px

cancelados = df_gold[
    df_gold["Cancelamento"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .isin(["sim", "yes", "true", "1"])
]

cancelamentos_por_contrato = (
    cancelados["Contrato"]
    .value_counts()
    .rename_axis("Contrato")
    .reset_index(name="Cancelamentos")
    .sort_values("Cancelamentos", ascending=True)
)

fig = px.bar(
    cancelamentos_por_contrato,
    x="Cancelamentos",
    y="Contrato",
    orientation="h",
    color="Cancelamentos",
    text="Cancelamentos",
    color_continuous_scale=["#BFDBFE", "#1D4ED8"],
    title="Cancelamentos por tipo de contrato",
    labels={
        "Contrato": "Tipo de contrato",
        "Cancelamentos": "Quantidade de clientes",
    },
    template="plotly_white",
)

fig.update_traces(
    textposition="outside",
    hovertemplate=(
        "<b>Contrato %{y}</b><br>"
        "Cancelamentos: %{x}<extra></extra>"
    ),
)

fig.update_layout(
    title_x=0.5,
    coloraxis_showscale=False,
    xaxis=dict(showgrid=True, gridcolor="#E5E7EB"),
    yaxis_title="",
    font=dict(family="Arial", size=13),
    margin=dict(l=30, r=50, t=70, b=40),
)

# Abre o gráfico interativo no navegador
fig.show()

In [21]:
import plotly.express as px

cancelados = df_gold[
    df_gold["Cancelamento"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .isin(["sim", "yes", "true", "1"])
]

cancelamentos_por_mes = (
    cancelados
    .dropna(subset=["DuracaoContrato"])
    .groupby("DuracaoContrato")
    .size()
    .reset_index(name="Cancelamentos")
    .sort_values("DuracaoContrato")
)

fig = px.bar(
    cancelamentos_por_mes,
    x="DuracaoContrato",
    y="Cancelamentos",
    color="Cancelamentos",
    color_continuous_scale="Plasma",
    title="Cancelamentos por tempo de contrato",
    labels={
        "DuracaoContrato": "Tempo de contrato (meses)",
        "Cancelamentos": "Quantidade de cancelamentos",
    },
    template="plotly_white",
)

fig.update_traces(
    hovertemplate=(
        "Tempo de contrato: %{x} meses<br>"
        "Cancelamentos: %{y}<extra></extra>"
    )
)

fig.update_layout(
    title_x=0.5,
    coloraxis_showscale=False,
    bargap=0.15,
    hovermode="x",
)

fig.update_xaxes(
    dtick=3,
    rangeslider_visible=True,
    showgrid=False,
)

fig.update_yaxes(
    rangemode="tozero",
    gridcolor="#E5E7EB",
)

fig.show()

In [23]:
import pandas as pd
import plotly.express as px

servicos = [
    "ServicoTelefonico",
    "MultiplasLinhas",
    "ServicoInternet",
    "SegurancaOnline",
    "BackupOnline",
    "ProtecaoDispositivo",
    "SuporteTecnico",
    "StreamingTV",
    "StreamingFilmes",
]

nomes = {
    "ServicoTelefonico": "Telefone",
    "MultiplasLinhas": "Múltiplas linhas",
    "ServicoInternet": "Internet",
    "SegurancaOnline": "Segurança online",
    "BackupOnline": "Backup online",
    "ProtecaoDispositivo": "Proteção do dispositivo",
    "SuporteTecnico": "Suporte técnico",
    "StreamingTV": "Streaming de TV",
    "StreamingFilmes": "Streaming de filmes",
}

cancelou = (
    df_gold["Cancelamento"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .isin(["sim", "yes", "true", "1"])
)
cancelados = df_gold.loc[cancelou]

positivos = {"sim", "yes", "true", "1"}
valores_sem_internet = {
    "não", "nao", "no", "false", "0",
    "no internet service", ""
}

contagem = {}

for coluna in servicos:
    valores = (
        cancelados[coluna]
        .astype("string")
        .str.strip()
        .str.casefold()
    )

    if coluna == "ServicoInternet":
        tinha_servico = valores.notna() & ~valores.isin(valores_sem_internet)
    else:
        tinha_servico = valores.isin(positivos)

    contagem[nomes[coluna]] = int(tinha_servico.sum())

dados_grafico = (
    pd.Series(contagem, name="Clientes")
    .rename_axis("Serviço")
    .reset_index()
    .sort_values("Clientes", ascending=True)
)

total_cancelados = len(cancelados)
dados_grafico["Percentual"] = (
    dados_grafico["Clientes"] / total_cancelados * 100
    if total_cancelados > 0
    else 0
)

fig = px.bar(
    dados_grafico,
    x="Clientes",
    y="Serviço",
    orientation="h",
    color="Clientes",
    text="Clientes",
    custom_data=["Percentual"],
    color_continuous_scale="Plasma",
    title="Serviços entre clientes que cancelaram",
    labels={
        "Clientes": "Quantidade de clientes",
        "Serviço": "",
    },
    template="plotly_white",
)

fig.update_traces(
    textposition="outside",
    hovertemplate=(
        "<b>%{y}</b><br>"
        "Clientes: %{x}<br>"
        "Percentual dos cancelados: %{customdata[0]:.1f}%"
        "<extra></extra>"
    ),
)

fig.update_layout(
    title_x=0.5,
    coloraxis_showscale=False,
    xaxis=dict(showgrid=True, gridcolor="#E5E7EB"),
    yaxis=dict(showgrid=False),
    margin=dict(l=30, r=45, t=70, b=40),
)

fig.show()

In [26]:
import pandas as pd
import plotly.express as px

colunas_servicos = [
    "ServicoTelefonico",
    "MultiplasLinhas",
    "ServicoInternet",
    "SegurancaOnline",
    "BackupOnline",
    "ProtecaoDispositivo",
    "SuporteTecnico",
    "StreamingTV",
    "StreamingFilmes",
]

nomes_servicos = {
    "ServicoTelefonico": "Telefone",
    "MultiplasLinhas": "Múltiplas linhas",
    "ServicoInternet": "Internet",
    "SegurancaOnline": "Segurança online",
    "BackupOnline": "Backup online",
    "ProtecaoDispositivo": "Proteção do dispositivo",
    "SuporteTecnico": "Suporte técnico",
    "StreamingTV": "Streaming de TV",
    "StreamingFilmes": "Streaming de filmes",
}

# Seleciona clientes que cancelaram
cancelou = (
    df_gold["Cancelamento"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .isin(["sim", "yes", "true", "1"])
)
clientes_cancelados = df_gold.loc[cancelou].copy()

if clientes_cancelados.empty:
    raise ValueError("Não foram encontrados clientes cancelados em df_gold.")

positivos = {"sim", "yes", "true", "1"}
negativos = {
    "não", "nao", "no", "false", "0", "",
    "none", "no internet service", "no phone service",
}

# Identifica os serviços ativos para cada cliente cancelado
servicos_ativos = pd.DataFrame(index=clientes_cancelados.index)

for coluna in colunas_servicos:
    valores = (
        clientes_cancelados[coluna]
        .astype("string")
        .str.strip()
        .str.casefold()
    )

    if coluna == "ServicoInternet":
        # Valores como DSL e Fiber optic indicam serviço de internet.
        servicos_ativos[coluna] = valores.notna() & ~valores.isin(negativos)
    else:
        servicos_ativos[coluna] = valores.isin(positivos)

# Resume a quantidade e os nomes dos serviços de cada cliente
analise_servicos = pd.DataFrame(index=clientes_cancelados.index)
analise_servicos["QuantidadeServicos"] = servicos_ativos.sum(axis=1)
analise_servicos["MaisDeUmServico"] = analise_servicos["QuantidadeServicos"] > 1
analise_servicos["Servicos"] = servicos_ativos.apply(
    lambda linha: [
        nomes_servicos[coluna]
        for coluna in colunas_servicos
        if linha[coluna]
    ],
    axis=1,
)

# Gráfico 1: clientes com até um serviço versus mais de um
analise_servicos["Grupo"] = analise_servicos["MaisDeUmServico"].map({
    False: "Até 1 serviço",
    True: "Mais de 1 serviço",
})

resumo = (
    analise_servicos["Grupo"]
    .value_counts()
    .reindex(["Até 1 serviço", "Mais de 1 serviço"], fill_value=0)
    .rename_axis("Grupo")
    .reset_index(name="Clientes")
)

fig_resumo = px.pie(
    resumo,
    names="Grupo",
    values="Clientes",
    hole=0.55,
    color="Grupo",
    color_discrete_map={
        "Até 1 serviço": "#93C5FD",
        "Mais de 1 serviço": "#2563EB",
    },
    title="Clientes cancelados por quantidade de serviços",
    template="plotly_white",
)

fig_resumo.update_traces(
    textinfo="label+percent",
    hovertemplate="<b>%{label}</b><br>Clientes: %{value}<extra></extra>",
)
fig_resumo.update_layout(title_x=0.5, legend_title_text="")
fig_resumo.show()

# Gráfico 2: combinações mais comuns entre quem tinha mais de um serviço
combinacoes = (
    analise_servicos.loc[analise_servicos["MaisDeUmServico"], "Servicos"]
    .apply(lambda lista: " + ".join(lista))
    .value_counts()
    .head(10)
    .sort_values()
    .rename_axis("Combinação de serviços")
    .reset_index(name="Clientes")
)

if not combinacoes.empty:
    fig_combinacoes = px.bar(
        combinacoes,
        x="Clientes",
        y="Combinação de serviços",
        orientation="h",
        text="Clientes",
        color="Clientes",
        color_continuous_scale="plasma",
        title="Combinações de serviços mais comuns",
        labels={"Clientes": "Clientes cancelados"},
        template="plotly_white",
    )

    fig_combinacoes.update_traces(
        textposition="outside",
        hovertemplate="<b>%{y}</b><br>Clientes: %{x}<extra></extra>",
    )
    fig_combinacoes.update_layout(
        title_x=0.5,
        coloraxis_showscale=False,
        yaxis_title="",
        xaxis=dict(showgrid=True, gridcolor="#E5E7EB"),
        margin=dict(l=30, r=40, t=70, b=40),
    )
    fig_combinacoes.show()
else:
    print("Não há clientes cancelados com mais de um serviço.")