# **Terra Telefonica**

## Importações

In [1]:
# instalação de pacotes (se necessários)
#%pip install pandas numpy matplotlib

In [2]:
# Importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

## Camada Bronze

In [3]:
# Leitura do arquivo CSV
df = pd.read_csv('history.csv', encoding="utf-8", sep=",")

In [4]:
df.shape

(5634, 23)

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

## Camada Silver

### Tradução e categorização das colunas

In [6]:
#Tradução dos nomes das colunas
df.rename(columns={
    "customerID": "id_cliente",
    "gender": "Genero",
    "SeniorCitizen": "Senioridade",
    "Partner": "Parceiro",
    "Dependents": "Dependentes",
    "tenure": "DuracaoContrato",
    "PhoneService": "ServicoTelefonico",
    "MultipleLines": "MultiplasLinhas",
    "InternetService": "ServicoInternet",
    "OnlineSecurity": "SegurancaOnline",
    "OnlineBackup": "BackupOnline",
    "DeviceProtection": "ProtecaoDispositivo",
    "TechSupport": "SuporteTecnico",
    "StreamingTV": "StreamingTV",
    "StreamingMovies": "StreamingFilmes",
    "Contract": "Contrato",
    "PaperlessBilling": "FaturaEletronica",
    "PaymentMethod": "MetodoPagamento",
    "MonthlyCharges": "CobrancaMensal",
    "TotalCharges": "CobrancaTotal",
    "Churn": "Cancelamento",
    "CustomerFeedback": "FeedbackCliente",
    "MonthlyIncome": "RendaMensal",
}, inplace=True)

In [7]:
df.head()

,id_cliente,Genero,Senioridade,Parceiro,Dependentes,DuracaoContrato,ServicoTelefonico,MultiplasLinhas,ServicoInternet,SegurancaOnline,...,StreamingTV,StreamingFilmes,Contrato,FaturaEletronica,MetodoPagamento,CobrancaMensal,CobrancaTotal,Cancelamento,FeedbackCliente,RendaMensal
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

In [8]:
# Verificando os tipos de dados das colunas
df.dtypes

id_cliente                 str
Genero                     str
Senioridade              int64
Parceiro                   str
Dependentes                str
DuracaoContrato            str
ServicoTelefonico          str
MultiplasLinhas            str
ServicoInternet            str
SegurancaOnline            str
BackupOnline               str
ProtecaoDispositivo        str
SuporteTecnico             str
StreamingTV                str
StreamingFilmes            str
Contrato                   str
FaturaEletronica           str
MetodoPagamento            str
CobrancaMensal         float64
CobrancaTotal          float64
Cancelamento               str
FeedbackCliente            str
RendaMensal              int64
dtype: object

In [9]:
# Categorização correta das colunas
df = df.astype({
    "Genero": "category",
    "Senioridade": "category",
    "Parceiro": "category",
    "Dependentes": "category",
    "ServicoTelefonico": "category",
    "MultiplasLinhas": "category",
    "ServicoInternet": "category",
    "SegurancaOnline": "category",
    "BackupOnline": "category",
    "ProtecaoDispositivo": "category",
    "SuporteTecnico": "category",
    "StreamingTV": "category",
    "StreamingFilmes": "category",
    "Contrato": "category",
    "FaturaEletronica": "category",
    "MetodoPagamento": "category",
    "Cancelamento": "category",
})

In [10]:
# Análise da coluna "DuracaoContrato"
df["DuracaoContrato"].value_counts(dropna=False)

DuracaoContrato
1          475
72         266
2          188
3          161
4          144
          ...
44          41
36          39
39          37
unknown     19
0           10
Name: count, Length: 74, dtype: int64

In [11]:
# Conversão da coluna "DuracaoContrato" para o tipo numérico, tratando valores não numéricos como NaN
df["DuracaoContrato"] = (
    pd.to_numeric(df["DuracaoContrato"], errors="coerce")
    .astype("Int64")
)

# Conversão das colunas restantes para os tipos de dados apropriados
df = df.astype({
    "id_cliente": "string",
    "CobrancaMensal": "float64",
    "CobrancaTotal": "float64",
    "FeedbackCliente": "string",
    "Senioridade": "Int64",
    "RendaMensal": "Int64",
    "DuracaoContrato": "Int64",
})

In [13]:
df.dtypes

id_cliente               string
Genero                 category
Senioridade               Int64
Parceiro               category
Dependentes            category
DuracaoContrato           Int64
ServicoTelefonico      category
MultiplasLinhas        category
ServicoInternet        category
SegurancaOnline        category
BackupOnline           category
ProtecaoDispositivo    category
SuporteTecnico         category
StreamingTV            category
StreamingFilmes        category
Contrato               category
FaturaEletronica       category
MetodoPagamento        category
CobrancaMensal          float64
CobrancaTotal           float64
Cancelamento           category
FeedbackCliente          string
RendaMensal               Int64
dtype: object

In [12]:
df.dtypes.map(lambda t: t.name).value_counts()

category    16
Int64        3
string       2
float64      2
Name: count, dtype: int64